create table if not exists public.appointment_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  branch text not null,
  preferred_date date not null,
  status text not null default 'new',
  notification_status text not null default 'pending',
  notified_at timestamptz
);

alter table public.appointment_requests enable row level security;

-- The website writes through the server-side Supabase service-role key.
-- No public/browser policy is created, so appointment records are not exposed to visitors.

create index if not exists appointment_requests_created_at_idx
  on public.appointment_requests (created_at desc);

create index if not exists appointment_requests_status_idx
  on public.appointment_requests (status);
